/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Daphne
 */
public class Ventana2 extends javax.swing.JFrame {
    String ruta = "";
    URL url = null;
    ImageIcon icon = null;
            
    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        lblOpcion = new javax.swing.JLabel();
        jcbOpciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstListado = new javax.swing.JList<>();
        btnLista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmVentana2"); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setText("Acceso Correcto!");
        jLabel1.setName("frmVentana2"); // NOI18N

        Regresar.setText("Atras");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        lblOpcion.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N

        jcbOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avengers", "The Big Bang Teory", "Thor" }));
        jcbOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOpcionesActionPerformed(evt);
            }
        });

        lstListado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Opcion 1", "Opcion 2", "Opcion 3", "Opcion 4", "Opcion 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstListado);

        btnLista.setText("Opcion");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Regresar)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jcbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLista)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(Regresar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        new Principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void jcbOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOpcionesActionPerformed
        // TODO add your handling code here:
        int op = jcbOpciones.getSelectedIndex();
        String cadena = jcbOpciones.getSelectedItem().toString();
        
        switch (op){
            case 0: this.mostrarImagen("/imagen/Imagen1.png", op+1, cadena);
                    //lblOpcion.setText("Seleccionó la opción 1");
                    /*JOptionPane.showMessageDialog(null, 
                    "Numero 1", "Opcion seleccionada", 
                    JOptionPane.INFORMATION_MESSAGE);
                    lblOpcion.setText("Selecciona la opción 1");
                    lblOpcion.setText(null);
                    lblOpcion.setIcon(new ImageIcon("src/imagen/Imagen1.png"));*/
                    
                    break;
                    
            case 1: this.mostrarImagen("/imagen/Imagen2.png", op+1, cadena);
                    //lblOpcion.setText("Seleccionó la opción 2");
                    /*JOptionPane.showMessageDialog(null, 
                    "Numero 2", "Opcion seleccionada", 
                    JOptionPane.INFORMATION_MESSAGE);
                    lblOpcion.setText("Selecciona la opción 2");
                    lblOpcion.setText(null);
                    lblOpcion.setIcon(new ImageIcon("src/imagen/Imagen2.png"));*/
                    
                    break;
                    
            case 2: this.mostrarImagen("/imagen/Imagen3.png", op+1, cadena);
                    //lblOpcion.setText("Seleccionó la opción 3");
                    /*JOptionPane.showMessageDialog(null, 
                    "Numero 3", "Opcion seleccionada", 
                    JOptionPane.INFORMATION_MESSAGE);
                    //lblOpcion.setText("Selecciona la opción 3");
                    lblOpcion.setText(null);
                    lblOpcion.setIcon(new ImageIcon("src/imagen/Imagen3.png"));*/
            break;
            
            
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jcbOpcionesActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
        int opc = lstListado.getSelectedIndex();
        
        switch(opc){
            case -1:  
            JOptionPane.showMessageDialog(null, "Selecciona una opcion ",
                                        "ERROR!!", JOptionPane.ERROR_MESSAGE);
            break;
            case 0:
                     
            case 1:
            
            case 2:
                          
            case 3:
            
            case 4: mostrarCuadro(opc+1);
            
            break;
        }
            
        
    }//GEN-LAST:event_btnListaActionPerformed
        public void mostrarCuadro(int opc){
        JOptionPane.showMessageDialog(null, "Opcion No: " +opc,
                                        "Opcion seleccionada", JOptionPane.INFORMATION_MESSAGE);   
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }
    
    public void mostrarImagen(String urlImagen, int opcion, String cad){
        ruta = urlImagen;
        url = this.getClass().getResource(ruta);
        icon = new ImageIcon(url);
        lblOpcion.setIcon(icon);
        lblOpcion.setText("Seleccionó la opción: " +opcion);
        lblOpcion.setText("Opcion:" +opcion + "Texto: " +cad);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar;
    private javax.swing.JButton btnLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbOpciones;
    private javax.swing.JLabel lblOpcion;
    private javax.swing.JList<String> lstListado;
    // End of variables declaration//GEN-END:variables
}
